services:
  breedbase:
    container_name: breedbase_web
    image: breedbase/breedbase:latest
    environment:
      USER_GROUP_ID: ${USER_GROUP_ID:?}
    volumes:
      - webdata:/home/production/volume
    ports:
      - 8080:8080
    depends_on:
      breedbase_db:
        condition: service_healthy

    healthcheck:
      test: curl -I localhost:8080
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  breedbase_db:
    container_name: breedbase_db
    volumes:
      - dbdata:/var/lib/postgresql/data
    image: postgres:12.7
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -q postgres -c '\\dt'"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  webdata:
  dbdata:
